version = 1

[[analyzers]]
name = "docker"
enabled = true

[analyzers.meta]
dockerfile_paths = ["Dockerfile", "goreleaser.Dockerfile"]

[[analyzers]]
name = "go"
enabled = true

[analyzers.meta]
import_root = "github.com/divideprojects/RestrictChannelRobot"
dependencies_vendored = true
